apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.sigs.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes-sigs/scheduler-plugins/pull/50"
spec:
  group: scheduling.sigs.k8s.io
  names:
    kind: PodGroup
    plural: podgroups
    singular: podgroup
    shortNames:
    - pg
    - pgs
  scope: Namespaced
  versions:
  - name: "v1alpha1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              minMember:
                type: integer
                minimum: 1
              scheduleTimeoutSeconds:
                type: integer
              minResources:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              phase:
                type: string
              occupiedBy:
                type: string
              scheduled:
                type: integer
                default: 0
              running:
                type: integer
                default: 0
              succeeded:
                type: integer
                default: 0
              failed:
                type: integer
                default: 0
              scheduleStartTime:
                type: string
                format: date-time

